# site settings
title: Kyokushin Karate
subtitle: //
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# user details
email: zilsmc@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 7888
country: United States of America
phone: (716) 555-5555



author: Max-Andre Zils

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
instagram_url: https://instagram.com
pinterest_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
